### ISSUE TITLE
Breaks with C++11

### ISSUE THREAD

**Issue by Flamefire** [CovenantEyes/boost-nowide#1]
Unfortunately this breaks with `-std=c++11` due to undefined `_wfopen` etc.

You'd probably need to undef `__STRICT_ANSI__` to make it work again.

**Comment by toddrobinsonce** [comment]
Thanks for the note, this doesn't seem to be used anymore, so we're archiving the repository.

**Comment by Flamefire** [comment]
FYI: nowide is part of boost now: https://github.com/boostorg/nowide

There is also a standalone version (branch and releases) and it works with c++11.

Would be great if you could add a note /link so others find it

**Comment by toddrobinsonce** [comment]
Done, thanks.
